app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("", home, name="home"),
    path("post_detail/<int:pk>", post_detail, name="post_detail"),
    path("post_create/", post_create, name="post_create"),
    path("post_delete/<int:pk>", post_delete, name="post_delete"),
    path("post_edit/<int:pk>", post_edit, name="post_edit"),
    path("forbidden/", forbidden, name="forbidden"),
    path("not_found/", not_found, name="not_found"),
    path("post_like/<int:pk>", post_like, name="post_like"),
    path("post_dislike/<int:pk>", post_dislike, name="post_dislike"),
    path("comment_edit/<int:pk>", comment_edit, name="comment_edit"),
    path("comment_delete/<int:pk>", comment_delete, name="comment_delete"),
    path('comment_like/<int:pk>', comment_like, name='comment_like'),
    path('comment_dislike/<int:pk>', comment_dislike, name='comment_dislike'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("app.urls", "app"), namespace="app")),
    path("users/", include(("users.urls", "users"), namespace="users")),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Введите ваш юзернейм"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Придумайте пароль"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Повторите пароль"})
    )

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Введите ваш юзернейм"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Введите пароль"})
    )

    class Meta:
        model = User
        fields = ["username", "password"]

users/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import login, logout

def register(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        return redirect("users:login")

    return render(request, "register.html", {"form": form})

def log_in(request):
    form = LoginForm(data=request.POST or None)

    if form.is_valid() and request.method == "POST":
        user = form.get_user()
        login(request, user)
        return redirect("app:home")

    return render(request, "login.html", {"form": form})

def log_out(request):
    if request.method == "POST":
        logout(request)
        return redirect("users:login")

    return render(request, "logout.html")

users/templates/login.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="form">
  <form action="" method="post" enctype="multipart/form-data" style="width: 30vw">
    {% csrf_token %}
    {% for field in form %}

    <div class="field">
      {{ field }}
    </div>
    {% endfor %}

    <div class="redirect" style="text-align: right;">Перейти на страницу 
      <a href="{% url 'users:register' %}">регистрации</a>
    </div>
    <button>Войти</button>
  </form>
</div>
{% endblock %}

users/templates/logout.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="form">
  <form method="post">
    {% csrf_token %}
    <div class="title">Вы уверены что хотите выйти?</div>

    <div class="buttons">
      <button class="button danger">
        <ion-icon name="checkmark-circle-outline"></ion-icon>
      </button>
      <a class="button primary" href="{% url 'app:home' %}">
        <ion-icon name="close-circle-outline"></ion-icon>
      </a>
    </div>
  </form>
</div>
{% endblock %}

users/templates/register.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="form">
  <form action="" method="post" enctype="multipart/form-data" style="width: 30vw">
    {% csrf_token %}
    {% for field in form %}

    <div class="field">
      {{ field }}
    </div>
    {% endfor %}
    <div class="redirect" style="text-align: right;">Перейти на страницу 
      <a href="{% url 'users:login' %}">входа</a>
    </div>
    <button>Зарегистрироваться</button>
  </form>
</div>
{% endblock %}