app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("", home, name="home"),
    path("post_detail/<int:pk>", post_detail, name="post_detail"),
    path("post_create/", post_create, name="post_create"),
    path("post_delete/<int:pk>", post_delete, name="post_delete"),
    path("post_edit/<int:pk>", post_edit, name="post_edit"),
    path("forbidden/", forbidden, name="forbidden"),
    path("not_found/", not_found, name="not_found"),
    path("post_like/<int:pk>", post_like, name="post_like"),
    path("post_dislike/<int:pk>", post_dislike, name="post_dislike"),
    path("comment_edit/<int:pk>", comment_edit, name="comment_edit"),
    path("comment_delete/<int:pk>", comment_delete, name="comment_delete"),
    path('comment_like/<int:pk>', comment_like, name='comment_like'),
    path('comment_dislike/<int:pk>', comment_dislike, name='comment_dislike'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("app.urls", "app"), namespace="app")),
    path("users/", include(("users.urls", "users"), namespace="users")),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    author = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE, default=1
    )
    date_added = models.DateField(auto_now_add=True)
    image = models.ImageField(default="default.png", blank=True)
    likes = models.ManyToManyField(User, related_name="likes")
    dislikes = models.ManyToManyField(User, related_name="dislikes")


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:20].strip()

class Comment(models.Model):
    body = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    is_edited = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField('auth.User', related_name='comment_likes')
    dislikes = models.ManyToManyField('auth.User', related_name='comment_dislikes')
    parent = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE, related_name='reply'
    )
    first_comment = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE, related_name='main_comment'
    )

    def __str__(self):
        return self.body

app/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>
    <script src="{% static 'script.js' %}" defer></script>
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="navbar-start">
          <a class="navbar-logo" href="{% url 'app:home' %}">
            <img
              src="https://msk.top-academy.ru/dist/images/logo/step_logo_rus.svg"
              alt=""
            />
          </a>
        </div>
        <div class="navbar-menu">
          <div class="navbar-item">
            {% if user.is_authenticated %}
            <a class="button" href="{% url 'app:post_create' %}">
              Создать пост
            </a>
            {% endif %}
          </div>
          <div class="navbar-item">
            {% if user.is_authenticated %}
            <a class="button" href="{% url 'users:logout' %}">Выйти</a>
            {% else %}
            <a class="button" href="{% url 'users:login' %}">Войти</a>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

app/templates/comment_delete.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="form">
  <form method="post">
    {% csrf_token %}
    <div class="title">Подтвердите удаление комментария</div>

    <div class="buttons">
      <button class="button danger">
        <ion-icon name="checkmark-circle-outline"></ion-icon>
      </button>
      <a class="button primary" href="{% url 'app:post_detail' comment.post.pk %}">
        <ion-icon name="close-circle-outline"></ion-icon>
      </a>
    </div>
  </form>
</div>
{% endblock %}

app/templates/forbidden.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="container">
  <div class="flex-container">
    <div class="image">
      <img src="https://cdni.iconscout.com/illustration/premium/thumb/error-403-illustration-download-in-svg-png-gif-file-formats--forbidden-client-website-http-web-empty-pages-pack-user-interface-illustrations-6588413.png" alt="" />
    </div>
    <div class="text">
      <div class="title">
        Кажется, у вас нет прав <br>
        на выполнения этого действия
      </div>
      <a href="{% url 'app:home' %}" class="button">На главную</a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container-home">
  {% for post in posts %}
  <a class="post" href="{% url 'app:post_detail' post.id %}">
    <div>
      <div class="title">{{post.title}}</div>
      <div class="author">Опубликовано: {{post.author}}</div>
    </div>
    <div>
      <div class="text">{{post.snippet}}...</div>
      <div class="date">{{post.date_added}}</div>
      <div class="post-data">
        <div class="post-likes">
          <ion-icon name="thumbs-up"></ion-icon>
          {{post.likes.count}}
        </div>
        <div class="post-dislikes">
          <ion-icon name="thumbs-down"></ion-icon>
          {{post.dislikes.count}}
        </div>
        <div class="post-comments">
          <ion-icon name="chatbubble"></ion-icon>
          {{post.comment_set.count}}
        </div>
      </div>
    </div>
  </a>
  {% endfor %}
</div>

{% if posts.count < all_posts %}
<div class="show-more">
  <a href="{% url 'app:home' %}?quantity={{posts.count|add:3}}" class="button primary">
    Показать еще
  </a>
</div>
{% endif %}
{% endblock %}

app/templates/post.html
{% extends 'base_layout.html' %} {% block content %}
<div class="post-container">
  <div class="header">
    <div>
      <div class="title">{{ post.title }}</div>
      <div class="info">{{post.date_added}} by {{post.author}}</div>
    </div>

    {% if user == post.author %}
    <div class="buttons">
      <a class="button primary" href="{% url 'app:post_edit' post.pk %}">
        <ion-icon name="create-outline"></ion-icon>
      </a>
      <a class="button danger" href="{% url 'app:post_delete' post.pk %}">
        <ion-icon name="trash-outline"></ion-icon>
      </a>
    </div>
    {% endif %}
  </div>

  <div class="image">
    <img src="{{ post.image.url }}" alt="" />
  </div>
  <div class="post-body">{{ post.body }}</div>
  <hr />
  <div class="post-buttons">
    <a href="{% url 'app:post_like' post.pk %}" class="post-button {% if user in post.likes.all %} primary {% endif %}">
      <ion-icon name="thumbs-up-outline"></ion-icon>
      <span> {{ post.likes.count }}</span>
    </a>
    <a href="{% url 'app:post_dislike' post.pk %}"
      class="post-button {% if user in post.dislikes.all %} danger {% endif %}">
      <ion-icon name="thumbs-down-outline"></ion-icon>
      <span> {{ post.dislikes.count }}</span>
    </a>
  </div>
  <hr />
  <div class="comments">
    {% if post.comment_set.all %}
    <div class="title">Комментарии: {{ post.comment_set.count }}</div>
    {% else %}
    <div class="title">Пока нет комментариев</div>
    {% endif %}

    <form method="post" class="comment-form">
      {% csrf_token %} {% for field in form %} {{field}} {% endfor %}
    </form>

    <div class="comments-container">
      {% for comment in comments %}
      <div class="comment">
        <div class="comment-head">
          <div class="comment-author">
            <div class="avatar">
              <img src="https://static-00.iconduck.com/assets.00/avatar-default-icon-2048x2048-h6w375ur.png" alt="" />
            </div>
            <div class="author-data">
              <div class="author-name">{{ comment.author }}</div>
              <div class="date">{{ comment.date_added }}</div>
            </div>
          </div>
        </div>
        <div class="comment-body">
          <div>{{ comment.body }}</div>
          <div class="is-edited">
            {% if comment.is_edited %}
            <span>Изменено</span>
            {% endif %}
          </div>
        </div>
        <div class="comment-footer">
          <div class="buttons">
            <a href="{% url 'app:comment_like' comment.pk %}"
              class="btn {% if user in comment.likes.all %} primary {% endif %}">
              <ion-icon name="thumbs-up-outline"></ion-icon>
              {{comment.likes.count}}
            </a>
            <a href="{% url 'app:comment_dislike' comment.pk %}"
              class="btn {% if user in comment.dislikes.all %} danger {% endif %}">
              <ion-icon name="thumbs-down-outline"></ion-icon>
              {{comment.likes.count}}
            </a>
          </div>
          <div class="comment-control">
            {% if user == comment.author or user.is_superuser %}
            <a class="btn primary" href="{% url 'app:comment_edit' comment.pk %}">
              <ion-icon name="create"></ion-icon>
            </a>
            <a class="btn danger" href="{% url 'app:comment_delete' comment.pk %}">
              <ion-icon name="trash"></ion-icon>
            </a>
            {% endif %}
            <button class="btn" onclick="toggleReplyForm('comment-{{comment.pk}}')">
              <ion-icon name="arrow-undo"></ion-icon>
            </button>
          </div>
        </div>
        <div class="is-hidden" id="comment-{{comment.pk}}">
          <form method="post" class="comment-form">
            {% csrf_token %}
            <input type="hidden" value="{{comment.pk}}" name="parent_id">
            {% for field in form %}
            {{field}}
            {% endfor %}
          </form>

          <hr>

          {% for reply in comment.main_comment.all %}
          <div class="reply">
            <div class="comment-head">
              <div class="comment-author">
                <div class="avatar">
                  <img src="https://static-00.iconduck.com/assets.00/avatar-default-icon-2048x2048-h6w375ur.png"
                    alt="" />
                </div>
                <div class="author-data">
                  <div class="author-name">{{ reply.author }}</div>
                  <div class="date">{{ reply.date_added }}</div>
                </div>
              </div>
            </div>
            <div class="comment-body">
              <div>
                <strong>{{reply.parent.author}},</strong>
                <span>{{ reply.body }}</span>
              </div>
              <div class="is-edited">
                {% if reply.is_edited %}
                <span>Изменено</span>
                {% endif %}
              </div>
            </div>
            <div class="comment-footer">
              <div class="buttons">
                <a href="{% url 'app:comment_like' reply.pk %}"
                  class="btn {% if user in reply.likes.all %} primary {% endif %}">
                  <ion-icon name="thumbs-up-outline"></ion-icon>
                  {{reply.likes.count}}
                </a>
                <a href="{% url 'app:comment_dislike' reply.pk %}"
                  class="btn {% if user in reply.dislikes.all %} danger {% endif %}">
                  <ion-icon name="thumbs-down-outline"></ion-icon>
                  {{reply.likes.count}}
                </a>
              </div>
              <div class="comment-control">
                {% if user == reply.author or user.is_superuser %}
                <a class="btn primary" href="{% url 'app:comment_edit' reply.pk %}">
                  <ion-icon name="create"></ion-icon>
                </a>
                <a class="btn danger" href="{% url 'app:comment_delete' reply.pk %}">
                  <ion-icon name="trash"></ion-icon>
                </a>
                {% endif %}
                <button class="btn" onclick="toggleReplyForm('comment-{{reply.pk}}')">
                  <ion-icon name="arrow-undo"></ion-icon>
                </button>
              </div>
            </div>
            
            <div class="is-hidden" id="comment-{{reply.pk}}">
              <form method="post" class="comment-form">
                {% csrf_token %}
                <input type="hidden" value="{{reply.pk}}" name="parent_id">
                {% for field in form %}
                {{field}}
                {% endfor %}
              </form>
            </div>
          </div>
          <hr>
          {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% if comments.has_other_pages %}
  <div class="pagination-buttons">
    <div class="previous">
      {% if comments.has_previous %}
      <a href="{%  url 'app:post_detail' post.pk %}?page=1" class="button">В начало</a>
      <a href="{% url 'app:post_detail' post.pk %}?page={{comments.previous_page_number}}" class="button">Назад</a>
      {% endif %}
    </div>
    <div class="page-number">{{comments.number}}</div>
    <div class="next">
      {% if comments.has_next %}
      <a href="{% url 'app:post_detail' post.pk %}?page={{comments.next_page_number}}" class="button">Далее</a>
      <a href="{%  url 'app:post_detail' post.pk %}?page={{comments.paginator.num_pages}}" class="button">
        В конец
      </a>
      {% endif %}
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

app/templates/post_create.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="form">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}

    <div class="field">
      {{ field }}
    </div>
    {% endfor %}
    <button>Сохранить</button>
  </form>
</div>
{% endblock %}

app/templates/post_delete.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="form">
  <form method="post">
    {% csrf_token %}
    <div class="title">Подтвердите удаление поста</div>

    <div class="buttons">
      <button class="button danger">
        <ion-icon name="checkmark-circle-outline"></ion-icon>
      </button>
      <a class="button primary" href="{% url 'app:home' %}">
        <ion-icon name="close-circle-outline"></ion-icon>
      </a>
    </div>
  </form>
</div>
{% endblock %}

app/templates/post_edit.html
{% extends 'base_layout.html' %} 

{% block content %}
<div class="form">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}

    <div class="field">
      {{ field }}
    </div>
    {% endfor %}
    <button>Сохранить</button>
  </form>
</div>
{% endblock %}